import type {
  BuildingType,
  CurrentStage,
  FounderRole,
  LookingForRole,
  PartnershipGoal,
} from "@/types/onboarding";

export type SeedFounder = {
  email: string;
  name: string;
  founderRole: FounderRole;
  buildingFocus: BuildingType;
  currentStage: CurrentStage;
  lookingForRoles: LookingForRole[];
  partnershipGoals?: PartnershipGoal[];
  country: string;
  city: string;
  headline: string;
  bio: string;
  skills: string[];
  yearsExperience: number;
  companyName: string;
  linkedinUrl: string;
  websiteUrl?: string;
  profilePhotoUrl?: string;
  isDemo?: boolean;
};

export const SEED_PASSWORD = "Password@123";

export const SEED_FOUNDERS: SeedFounder[] = [
  {
    email: "doctor@splice.dev",
    name: "Dr. Ananya Sharma",
    founderRole: "doctor",
    buildingFocus: "diagnostics",
    currentStage: "mvp",
    lookingForRoles: ["engineer", "business"],
    country: "India",
    city: "Bengaluru",
    headline: "Building point-of-care diagnostics for tier-2 clinics",
    bio: "Interventional cardiologist turned founder focused on affordable cardiac screening workflows for community hospitals across Karnataka.",
    skills: ["Clinical validation", "Regulatory strategy", "Hospital partnerships"],
    yearsExperience: 11,
    companyName: "PulseBridge Diagnostics",
    linkedinUrl: "https://linkedin.com/in/ananya-sharma-md",
    websiteUrl: "https://pulsebridge.health",
    isDemo: true,
  },
  {
    email: "engineer@splice.dev",
    name: "Rohan Mehta",
    founderRole: "engineer",
    buildingFocus: "medical-device",
    currentStage: "prototype",
    lookingForRoles: ["doctor", "business"],
    country: "India",
    city: "Pune",
    headline: "Embedded systems for wearable cardiac monitoring",
    bio: "Biomedical engineer with deep firmware experience building low-power devices for continuous vitals in ambulatory care.",
    skills: ["Embedded systems", "Signal processing", "Hardware prototyping"],
    yearsExperience: 9,
    companyName: "CardioSense Labs",
    linkedinUrl: "https://linkedin.com/in/rohan-mehta-bme",
    websiteUrl: "https://cardiosense.dev",
    isDemo: true,
  },
  {
    email: "business@splice.dev",
    name: "Priya Nair",
    founderRole: "business",
    buildingFocus: "healthcare-saas",
    currentStage: "revenue",
    lookingForRoles: ["engineer", "designer"],
    country: "India",
    city: "Mumbai",
    headline: "SaaS for outpatient clinic operations in India",
    bio: "Former healthcare operator scaling scheduling, billing, and patient communication tools for multi-specialty clinics.",
    skills: ["GTM strategy", "Healthcare ops", "Enterprise sales"],
    yearsExperience: 12,
    companyName: "ClinicFlow",
    linkedinUrl: "https://linkedin.com/in/priya-nair-healthops",
    websiteUrl: "https://clinicflow.in",
    isDemo: true,
  },
  {
    email: "researcher@splice.dev",
    name: "Dr. Arjun Desai",
    founderRole: "researcher",
    buildingFocus: "biotech",
    currentStage: "idea",
    lookingForRoles: ["business", "investor"],
    country: "India",
    city: "Hyderabad",
    headline: "Novel biomarkers for early liver fibrosis detection",
    bio: "Translational researcher moving lab discoveries into commercially viable diagnostic panels for hepatology programs.",
    skills: ["Biomarker discovery", "Clinical research", "IP strategy"],
    yearsExperience: 10,
    companyName: "FibroScan Labs",
    linkedinUrl: "https://linkedin.com/in/arjun-desai-phd",
    isDemo: true,
  },
  {
    email: "investor@splice.dev",
    name: "Meera Kapoor",
    founderRole: "investor",
    buildingFocus: "digital-health",
    currentStage: "scaling",
    lookingForRoles: ["doctor", "engineer", "business"],
    country: "India",
    city: "Delhi",
    headline: "Angel investor in Indian digital health startups",
    bio: "Former VC associate backing early-stage founders building regulated health products with strong clinical pull.",
    skills: ["Fundraising", "Market sizing", "Board advisory"],
    yearsExperience: 14,
    companyName: "Kapoor Health Ventures",
    linkedinUrl: "https://linkedin.com/in/meera-kapoor-invest",
    websiteUrl: "https://kapoorhealth.vc",
    isDemo: true,
  },
  {
    email: "kavya.iyer@splice.dev",
    name: "Kavya Iyer",
    founderRole: "engineer",
    buildingFocus: "ai-healthcare",
    currentStage: "mvp",
    lookingForRoles: ["doctor", "researcher"],
    country: "India",
    city: "Chennai",
    headline: "AI triage copilot for emergency departments",
    bio: "ML engineer building decision-support tools that help ED teams prioritize cases without replacing clinician judgment.",
    skills: ["Machine learning", "MLOps", "Clinical workflows"],
    yearsExperience: 7,
    companyName: "TriageMind AI",
    linkedinUrl: "https://linkedin.com/in/kavya-iyer-ml",
  },
  {
    email: "vikram.singh@splice.dev",
    name: "Vikram Singh",
    founderRole: "doctor",
    buildingFocus: "digital-health",
    currentStage: "revenue",
    lookingForRoles: ["engineer", "designer"],
    country: "India",
    city: "Chandigarh",
    headline: "Tele-dermatology for semi-urban India",
    bio: "Dermatologist expanding asynchronous consult workflows for patients who cannot access specialist care locally.",
    skills: ["Telemedicine", "Clinical protocols", "Patient education"],
    yearsExperience: 13,
    companyName: "DermaReach",
    linkedinUrl: "https://linkedin.com/in/vikram-singh-derm",
  },
  {
    email: "neha.patel@splice.dev",
    name: "Neha Patel",
    founderRole: "designer",
    buildingFocus: "digital-health",
    currentStage: "prototype",
    lookingForRoles: ["engineer", "business"],
    country: "India",
    city: "Ahmedabad",
    headline: "Patient-friendly UX for chronic care apps",
    bio: "Product designer specializing in accessible health interfaces for elderly users managing diabetes and hypertension.",
    skills: ["UX research", "Design systems", "Accessibility"],
    yearsExperience: 8,
    companyName: "CareCanvas Studio",
    linkedinUrl: "https://linkedin.com/in/neha-patel-ux",
  },
  {
    email: "amit.choudhury@splice.dev",
    name: "Amit Choudhury",
    founderRole: "engineer",
    buildingFocus: "medical-device",
    currentStage: "mvp",
    lookingForRoles: ["doctor", "investor"],
    country: "India",
    city: "Kolkata",
    headline: "Affordable neonatal warming devices",
    bio: "Mechanical engineer developing rugged infant warmers for district hospitals with unreliable power infrastructure.",
    skills: ["Mechanical design", "Manufacturing", "Field testing"],
    yearsExperience: 10,
    companyName: "WarmStart Devices",
    linkedinUrl: "https://linkedin.com/in/amit-choudhury-devices",
  },
  {
    email: "sana.qureshi@splice.dev",
    name: "Dr. Sana Qureshi",
    founderRole: "doctor",
    buildingFocus: "pharma",
    currentStage: "idea",
    lookingForRoles: ["researcher", "business"],
    country: "India",
    city: "Mumbai",
    headline: "Repurposed molecules for rare metabolic disorders",
    bio: "Pediatrician exploring orphan drug pathways with a focus on affordable treatment access in public hospitals.",
    skills: ["Pediatrics", "Clinical trials", "Regulatory affairs"],
    yearsExperience: 9,
    companyName: "MetaboKind Therapeutics",
    linkedinUrl: "https://linkedin.com/in/sana-qureshi-md",
  },
  {
    email: "dev.rastogi@splice.dev",
    name: "Dev Rastogi",
    founderRole: "engineer",
    buildingFocus: "diagnostics",
    currentStage: "prototype",
    lookingForRoles: ["doctor", "business"],
    country: "India",
    city: "Indore",
    headline: "Microfluidics for rapid TB screening",
    bio: "Instrumentation engineer building portable lab-on-chip systems for high-burden TB screening camps.",
    skills: ["Microfluidics", "Optics", "Quality systems"],
    yearsExperience: 6,
    companyName: "FlowDetect Labs",
    linkedinUrl: "https://linkedin.com/in/dev-rastogi-engineer",
  },
  {
    email: "lisa.fernandes@splice.dev",
    name: "Lisa Fernandes",
    founderRole: "business",
    buildingFocus: "marketplace",
    currentStage: "mvp",
    lookingForRoles: ["engineer", "designer"],
    country: "India",
    city: "Panaji",
    headline: "Marketplace for home healthcare professionals",
    bio: "Operator connecting verified nurses and physiotherapists with families needing post-operative home care.",
    skills: ["Marketplace ops", "Supply acquisition", "Compliance"],
    yearsExperience: 11,
    companyName: "HomeCare Circle",
    linkedinUrl: "https://linkedin.com/in/lisa-fernandes-ops",
  },
  {
    email: "harish.menon@splice.dev",
    name: "Harish Menon",
    founderRole: "researcher",
    buildingFocus: "diagnostics",
    currentStage: "mvp",
    lookingForRoles: ["engineer", "investor"],
    country: "India",
    city: "Cochin",
    headline: "Genomics panels for oncology screening",
    bio: "Molecular biologist translating genomic assays into clinically actionable reports for oncology centers.",
    skills: ["Genomics", "Bioinformatics", "Lab automation"],
    yearsExperience: 12,
    companyName: "OncoGenix Labs",
    linkedinUrl: "https://linkedin.com/in/harish-menon-genomics",
  },
  {
    email: "tanya.bose@splice.dev",
    name: "Tanya Bose",
    founderRole: "designer",
    buildingFocus: "medical-device",
    currentStage: "idea",
    lookingForRoles: ["engineer", "doctor"],
    country: "India",
    city: "Bengaluru",
    headline: "Human-centered surgical instrument design",
    bio: "Industrial designer collaborating with surgeons to simplify laparoscopic tool ergonomics for long procedures.",
    skills: ["Industrial design", "Human factors", "Prototyping"],
    yearsExperience: 7,
    companyName: "SurgiForm Design",
    linkedinUrl: "https://linkedin.com/in/tanya-bose-design",
  },
  {
    email: "imran.shaikh@splice.dev",
    name: "Imran Shaikh",
    founderRole: "engineer",
    buildingFocus: "ai-healthcare",
    currentStage: "revenue",
    lookingForRoles: ["doctor", "business"],
    country: "India",
    city: "Pune",
    headline: "Radiology AI for chest X-ray prioritization",
    bio: "Computer vision engineer deploying models that flag critical findings for radiologist review in high-volume centers.",
    skills: ["Computer vision", "DICOM pipelines", "Model validation"],
    yearsExperience: 8,
    companyName: "RadPriority AI",
    linkedinUrl: "https://linkedin.com/in/imran-shaikh-ai",
    websiteUrl: "https://radpriority.ai",
  },
  {
    email: "deepa.krishnan@splice.dev",
    name: "Dr. Deepa Krishnan",
    founderRole: "doctor",
    buildingFocus: "healthcare-saas",
    currentStage: "scaling",
    lookingForRoles: ["engineer", "investor"],
    country: "India",
    city: "Chennai",
    headline: "EHR workflows for multi-location dialysis chains",
    bio: "Nephrologist building specialty EHR modules that reduce documentation burden across dialysis center networks.",
    skills: ["Nephrology", "Clinical workflows", "Quality metrics"],
    yearsExperience: 15,
    companyName: "DialysisOne",
    linkedinUrl: "https://linkedin.com/in/deepa-krishnan-md",
  },
  {
    email: "karthik.reddy@splice.dev",
    name: "Karthik Reddy",
    founderRole: "business",
    buildingFocus: "medical-device",
    currentStage: "prototype",
    lookingForRoles: ["engineer", "doctor"],
    country: "India",
    city: "Hyderabad",
    headline: "Commercializing affordable insulin delivery devices",
    bio: "Healthtech operator with distribution experience across South India seeking a technical co-founder for device scale-up.",
    skills: ["Distribution", "Pricing strategy", "Hospital sales"],
    yearsExperience: 13,
    companyName: "InsulinPath",
    linkedinUrl: "https://linkedin.com/in/karthik-reddy-health",
  },
  {
    email: "pooja.saxena@splice.dev",
    name: "Pooja Saxena",
    founderRole: "researcher",
    buildingFocus: "biotech",
    currentStage: "prototype",
    lookingForRoles: ["business", "engineer"],
    country: "India",
    city: "Delhi",
    headline: "Cell therapy tools for wound healing",
    bio: "Biotech researcher developing scaffold materials that accelerate chronic wound closure in diabetic patients.",
    skills: ["Cell culture", "Biomaterials", "Preclinical studies"],
    yearsExperience: 9,
    companyName: "HealMatrix Bio",
    linkedinUrl: "https://linkedin.com/in/pooja-saxena-bio",
  },
  {
    email: "aditya.joshi@splice.dev",
    name: "Aditya Joshi",
    founderRole: "engineer",
    buildingFocus: "digital-health",
    currentStage: "mvp",
    lookingForRoles: ["designer", "business"],
    country: "India",
    city: "Mumbai",
    headline: "Remote monitoring stack for cardiac rehab",
    bio: "Full-stack engineer building connected platforms that help cardiologists track recovery after intervention.",
    skills: ["Full-stack", "IoT integrations", "HIPAA-minded architecture"],
    yearsExperience: 9,
    companyName: "RehabPulse",
    linkedinUrl: "https://linkedin.com/in/aditya-joshi-dev",
  },
  {
    email: "ritu.malhotra@splice.dev",
    name: "Ritu Malhotra",
    founderRole: "business",
    buildingFocus: "diagnostics",
    currentStage: "revenue",
    lookingForRoles: ["doctor", "engineer"],
    country: "India",
    city: "Jaipur",
    headline: "Franchise model for diagnostic collection centers",
    bio: "Operator scaling sample collection networks in Rajasthan with standardized quality and logistics playbooks.",
    skills: ["Franchise ops", "Logistics", "Unit economics"],
    yearsExperience: 10,
    companyName: "LabReach Network",
    linkedinUrl: "https://linkedin.com/in/ritu-malhotra-ops",
  },
  {
    email: "sanjeet.bhatt@splice.dev",
    name: "Sanjeet Bhatt",
    founderRole: "doctor",
    buildingFocus: "ai-healthcare",
    currentStage: "prototype",
    lookingForRoles: ["engineer", "researcher"],
    country: "India",
    city: "Dehradun",
    headline: "Clinical decision support for rural primary care",
    bio: "Family physician building AI-assisted protocols for frontline workers managing mixed outpatient caseloads.",
    skills: ["Primary care", "Public health", "Clinical education"],
    yearsExperience: 12,
    companyName: "PrimaryAI Care",
    linkedinUrl: "https://linkedin.com/in/sanjeet-bhatt-md",
  },
  {
    email: "elena.varghese@splice.dev",
    name: "Elena Varghese",
    founderRole: "engineer",
    buildingFocus: "healthcare-saas",
    currentStage: "scaling",
    lookingForRoles: ["business", "designer"],
    country: "India",
    city: "Bengaluru",
    headline: "API infrastructure for health app integrations",
    bio: "Platform engineer making it easier for Indian health apps to exchange patient-consented data securely.",
    skills: ["API design", "Security", "Developer experience"],
    yearsExperience: 11,
    companyName: "HealthBridge API",
    linkedinUrl: "https://linkedin.com/in/elena-varghese-platform",
    websiteUrl: "https://healthbridge.dev",
  },
  {
    email: "rajesh.kapoor@splice.dev",
    name: "Dr. Rajesh Kapoor",
    founderRole: "doctor",
    buildingFocus: "diagnostics",
    currentStage: "mvp",
    lookingForRoles: ["doctor", "researcher"],
    country: "India",
    city: "Delhi",
    headline: "Clinical lead for chronic kidney screening panels",
    bio: "Nephrologist seeking another clinical co-founder to co-design protocol-first diagnostics for CKD progression.",
    skills: ["Nephrology", "Clinical protocols", "Hospital GTM"],
    yearsExperience: 14,
    companyName: "RenalScreen Labs",
    linkedinUrl: "https://linkedin.com/in/rajesh-kapoor-neph",
  },
  {
    email: "sameer.agarwal@splice.dev",
    name: "Sameer Agarwal",
    founderRole: "doctor",
    buildingFocus: "digital-health",
    currentStage: "revenue",
    lookingForRoles: ["engineer", "business"],
    country: "India",
    city: "Bengaluru",
    headline: "Digital pathways for outpatient chronic care",
    bio: "Physician operator scaling chronic care programs across outpatient networks in Karnataka.",
    skills: ["Chronic care", "Care pathways", "Clinical ops"],
    yearsExperience: 12,
    companyName: "ContinuumCare",
    linkedinUrl: "https://linkedin.com/in/sameer-agarwal-md",
  },
  {
    email: "nisha.verma@splice.dev",
    name: "Nisha Verma",
    founderRole: "business",
    buildingFocus: "healthcare-saas",
    currentStage: "mvp",
    lookingForRoles: ["engineer", "designer"],
    country: "India",
    city: "Pune",
    headline: "Ops SaaS for multi-clinic billing in India",
    bio: "Operator-founder building workflow software for billing, inventory, and patient communication across clinic chains.",
    skills: ["Healthcare SaaS", "Billing ops", "Customer success"],
    yearsExperience: 9,
    companyName: "ClinicLedger",
    linkedinUrl: "https://linkedin.com/in/nisha-verma-saas",
  },
  {
    email: "aravind.reddy@splice.dev",
    name: "Aravind Reddy",
    founderRole: "engineer",
    buildingFocus: "ai-healthcare",
    currentStage: "prototype",
    lookingForRoles: ["doctor", "business"],
    country: "India",
    city: "Hyderabad",
    headline: "Edge AI for bedside monitoring in ICUs",
    bio: "ML systems engineer focused on low-latency inference for bedside monitoring in Indian ICUs.",
    skills: ["Edge AI", "Signal processing", "MLOps"],
    yearsExperience: 8,
    companyName: "BedsideAI",
    linkedinUrl: "https://linkedin.com/in/aravind-reddy-ai",
  },
];

export type SeedRelationship =
  | {
      type: "connect";
      from: string;
      to: string;
      mutual?: boolean;
      /** Pre-match intro from `from` → `to` (pending connects / match copy). */
      intro?: string;
      /** Pre-match intro from `to` → `from` when mutual. */
      introReply?: string;
    }
  | { type: "pass"; from: string; to: string };

export type SeedReport = {
  reporter: string;
  reported: string;
  reason:
    | "harassment"
    | "spam"
    | "fake_profile"
    | "inappropriate_content"
    | "fraud_or_scam"
    | "impersonation"
    | "other";
  description?: string;
};

export const SEED_REPORTS: SeedReport[] = [
  {
    reporter: "doctor@splice.dev",
    reported: "lisa.fernandes@splice.dev",
    reason: "fake_profile",
    description: "Profile claims hospital partnerships that could not be verified.",
  },
  {
    reporter: "engineer@splice.dev",
    reported: "sana.qureshi@splice.dev",
    reason: "spam",
    description: "Repeated unsolicited fundraising links in match messages.",
  },
  {
    reporter: "business@splice.dev",
    reported: "dev.rastogi@splice.dev",
    reason: "other",
    description: "Mismatch between stated regulatory stage and public filings.",
  },
];

export const SEED_RELATIONSHIPS: SeedRelationship[] = [
  // Mutual matches (chat threads seeded separately in seed-messages-data)
  { type: "connect", from: "doctor@splice.dev", to: "engineer@splice.dev", mutual: true },
  { type: "connect", from: "business@splice.dev", to: "researcher@splice.dev", mutual: true },
  { type: "connect", from: "kavya.iyer@splice.dev", to: "vikram.singh@splice.dev", mutual: true },
  { type: "connect", from: "imran.shaikh@splice.dev", to: "deepa.krishnan@splice.dev", mutual: true },
  { type: "connect", from: "amit.choudhury@splice.dev", to: "tanya.bose@splice.dev", mutual: true },
  { type: "connect", from: "dev.rastogi@splice.dev", to: "harish.menon@splice.dev", mutual: true },
  { type: "connect", from: "neha.patel@splice.dev", to: "aditya.joshi@splice.dev", mutual: true },
  { type: "connect", from: "karthik.reddy@splice.dev", to: "pooja.saxena@splice.dev", mutual: true },
  { type: "connect", from: "elena.varghese@splice.dev", to: "ritu.malhotra@splice.dev", mutual: true },
  { type: "connect", from: "sana.qureshi@splice.dev", to: "sanjeet.bhatt@splice.dev", mutual: true },
  // Pending outgoing connects with pre-match introductions
  {
    type: "connect",
    from: "investor@splice.dev",
    to: "doctor@splice.dev",
    intro:
      "Ananya — backing clinically led diagnostics is my focus. Impressed by PulseBridge's district hospital angle; happy to compare notes.",
  },
  {
    type: "connect",
    from: "investor@splice.dev",
    to: "engineer@splice.dev",
    intro:
      "Rohan, CardioSense's low-power monitoring thesis maps to portfolios I advise. Would like to connect before your next raise.",
  },
  {
    type: "connect",
    from: "nisha.verma@splice.dev",
    to: "elena.varghese@splice.dev",
    intro:
      "Elena — ClinicLedger needs consent-aware integrations across clinic chains. Your HealthBridge API looks like the missing piece.",
  },
  {
    type: "connect",
    from: "aravind.reddy@splice.dev",
    to: "doctor@splice.dev",
    intro:
      "Dr. Sharma — BedsideAI is building edge inference for ICU monitors. Looking for a clinical co-founder who knows Indian hospital workflows.",
  },
  {
    type: "connect",
    from: "sameer.agarwal@splice.dev",
    to: "business@splice.dev",
  },
  { type: "pass", from: "doctor@splice.dev", to: "lisa.fernandes@splice.dev" },
  { type: "pass", from: "engineer@splice.dev", to: "sana.qureshi@splice.dev" },
  { type: "pass", from: "business@splice.dev", to: "dev.rastogi@splice.dev" },
  { type: "pass", from: "researcher@splice.dev", to: "tanya.bose@splice.dev" },
  { type: "pass", from: "investor@splice.dev", to: "ritu.malhotra@splice.dev" },
];
